development: &default
  adapter: postgresql
  database: pay_with_tweet_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: pay_with_tweet_test
